import type { Metadata } from "next";
import Layout from "@/components/Layout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Layout />
            <main className="w-full h-full md:ps-64">
                <div className="m-auto max-w-[1200px] p-4 sm:p-6">
                    {children}
                </div>
            </main>
        </>
    );
}
