import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="w-full h-full p-3 flex items-center justify-center">
            <div className="w-full" style={{ maxWidth: "500px", alignSelf: "safe center" }}>
                {children}
            </div>
        </main>
    );
}
